services:
  app:
    build: .
    ports:
      - "61860:61860"
    environment:
      - PORT=61860
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=tcukeb6-tcukeb6
      - DB_NAME=dating_app
      - GIPHY_API_KEY=${GIPHY_API_KEY}
      - SERVER_IP=${SERVER_IP}
      - PUBLIC_VAPID_KEY=${PUBLIC_VAPID_KEY}
      - PRIVATE_VAPID_KEY=${PRIVATE_VAPID_KEY}
      - EMAIL=${EMAIL}
      - MYSQL_SSL_CA=/usr/src/app/certs/ca-cert.pem
      - MYSQL_SSL_CERT=/usr/src/app/certs/client-cert.pem
      - MYSQL_SSL_KEY=/usr/src/app/certs/client-key.pem
    volumes:
      - ./uploads:/usr/src/app/public/uploads
      - ./certs:/usr/src/app/certs:ro
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=tcukeb6-tcukeb6
      - MYSQL_DATABASE=dating_app
    command: >
      --ssl-ca=/etc/mysql/ssl/ca-cert.pem
      --ssl-cert=/etc/mysql/ssl/server-cert.pem
      --ssl-key=/etc/mysql/ssl/server-key.pem
      --require-secure-transport=ON
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./certs:/etc/mysql/ssl:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
