version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: tcukeb6-tcukeb6
      MYSQL_DATABASE: dating_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password --ssl=0

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "61860:61860"
    volumes:
      - app_uploads:/usr/src/app/public/uploads
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=tcukeb6-tcukeb6
      - DB_NAME=dating_app
      - GIPHY_API_KEY=${GIPHY_API_KEY:-dummy_key}
      - SERVER_IP=${SERVER_IP:-localhost}
      - PUBLIC_VAPID_KEY=${PUBLIC_VAPID_KEY:-dummy_key}
      - PRIVATE_VAPID_KEY=${PRIVATE_VAPID_KEY:-dummy_key}
      - EMAIL=${EMAIL:-test@example.com}
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
  app_uploads:
