version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tcukeb6-tcukeb6
      MYSQL_DATABASE: dating_app
      MYSQL_SSL_MODE: DISABLED
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
      --ssl=0
      --skip-ssl
      --ssl-mode=DISABLED
      --require-secure-transport=OFF
      --skip-ssl-setup
      --ssl-cipher=
      --tls-version=

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "61860:61860"
    volumes:
      - app_uploads:/usr/src/app/public/uploads
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=tcukeb6-tcukeb6
      - DB_NAME=dating_app
      - MYSQL_SSL_MODE=DISABLED
      - MYSQL_ATTR_SSL_VERIFY_SERVER_CERT=false
      - GIPHY_API_KEY=${GIPHY_API_KEY:-dummy_key}
      - SERVER_IP=${SERVER_IP:-localhost}
      - PUBLIC_VAPID_KEY=${PUBLIC_VAPID_KEY:-dummy_key}
      - PRIVATE_VAPID_KEY=${PRIVATE_VAPID_KEY:-dummy_key}
      - EMAIL=${EMAIL:-test@example.com}
    depends_on:
      - db

volumes:
  mysql_data:
  app_uploads:
