services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=tcukeb6-tcukeb6
      - MYSQL_DATABASE=dating_app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=tcukeb6-tcukeb6
      - MYSQL_TCP_PORT=3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --bind-address=0.0.0.0
      --init-file=/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptcukeb6-tcukeb6"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 60s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "61860:61860/tcp"
      - "8080:8080/tcp"
    environment:
      - PORT=61860
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=tcukeb6-tcukeb6
      - DB_NAME=dating_app
      - DOMAIN=bdomenech.freeboxos.fr
      - SERVER_IP=0.0.0.0
      - ACME_PORT=8080
      - GIPHY_API_KEY=${GIPHY_API_KEY:-dummy_key}
      - PUBLIC_VAPID_KEY=${PUBLIC_VAPID_KEY:-dummy_key}
      - PRIVATE_VAPID_KEY=${PRIVATE_VAPID_KEY:-dummy_key}
      - EMAIL=domenech.bruno@me.com
    volumes:
      - app_uploads:/usr/src/app/public/uploads
      - ./ssl:/usr/src/app/ssl
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
  app_uploads:
