services:
  app:
    build: .
    ports:
      - "61860:61860"
    environment:
      - PORT=61860
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=tcukeb6-tcukeb6
      - DB_NAME=dating_app
      - GIPHY_API_KEY=${GIPHY_API_KEY}
      - SERVER_IP=${SERVER_IP}
      - PUBLIC_VAPID_KEY=${PUBLIC_VAPID_KEY}
      - PRIVATE_VAPID_KEY=${PRIVATE_VAPID_KEY}
      - EMAIL=${EMAIL}
      - MYSQL_SSL_CA=/usr/src/app/certs/ca-cert.pem
      - MYSQL_SSL_CERT=/usr/src/app/certs/client-cert.pem
      - MYSQL_SSL_KEY=/usr/src/app/certs/client-key.pem
    volumes:
      - app_uploads:/usr/src/app/public/uploads
      - mysql_certs:/usr/src/app/certs:ro
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: tcukeb6-tcukeb6
      MYSQL_DATABASE: dating_app
      MYSQL_SSL_CERT: /etc/mysql/ssl/server-cert.pem
      MYSQL_SSL_KEY: /etc/mysql/ssl/server-key.pem
      MYSQL_SSL_CA: /etc/mysql/ssl/ca-cert.pem
    ports:
      - "3306:3306"
    command: >
      --ssl-ca=/etc/mysql/ssl/ca-cert.pem
      --ssl-cert=/etc/mysql/ssl/server-cert.pem
      --ssl-key=/etc/mysql/ssl/server-key.pem
      --ssl-cipher=TLSv1.2
      --tls-version=TLSv1.2
      --require-secure-transport=ON
      --log-error=/var/log/mysql/error.log
      --general-log=1
      --general-log-file=/var/log/mysql/general.log
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_certs:/etc/mysql/ssl:ro
      - mysql_logs:/var/log/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD", "--ssl-mode=REQUIRED"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
  mysql_certs:
  mysql_logs:
  app_uploads:
