services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tcukeb6-tcukeb6
      MYSQL_DATABASE: dating_app
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-ptcukeb6-tcukeb6", "-e", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "61860:61860"
      - "80:80"  # For ACME challenge
      - "443:443"  # For HTTPS
    environment:
      - PORT=61860
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=tcukeb6-tcukeb6
      - DB_NAME=dating_app
      - DOMAIN=t2m.vigilys.fr
      - SERVER_IP=0.0.0.0
      - ACME_PORT=80
      - GIPHY_API_KEY=${GIPHY_API_KEY:-dummy_key}
      - PUBLIC_VAPID_KEY=${PUBLIC_VAPID_KEY:-dummy_key}
      - PRIVATE_VAPID_KEY=${PRIVATE_VAPID_KEY:-dummy_key}
      - EMAIL=domenech.bruno@me.com
      - NODE_ENV=production
    volumes:
      - app_uploads:/usr/src/app/public/uploads
      - ./ssl:/usr/src/app/ssl
      - acme_data:/root/.acme.sh
    depends_on:
      - db

volumes:
  mysql_data:
  app_uploads:
  acme_data:
