version: '3.8'

services:
  app:
    build: .
    ports:
      - "61860:61860"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=tcukeb6-tcukeb6
      - DB_NAME=dating_app
      - GIPHY_API_KEY=${GIPHY_API_KEY:-dummy_key}
      - SERVER_IP=${SERVER_IP:-localhost}
      - PUBLIC_VAPID_KEY=${PUBLIC_VAPID_KEY:-dummy_key}
      - PRIVATE_VAPID_KEY=${PRIVATE_VAPID_KEY:-dummy_key}
      - EMAIL=${EMAIL:-test@example.com}
    volumes:
      - app_uploads:/usr/src/app/public/uploads
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: tcukeb6-tcukeb6
      MYSQL_DATABASE: dating_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sh:/mysql-init.sh
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - mysql_logs:/var/log/mysql
    command: /mysql-init.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
  mysql_logs:
  app_uploads:
